my_kilometrowka_homepage:
    path:     /
    defaults: { _controller: MyKilometrowkaBundle:Default:index }
    
my_kilometrowka_rejestracja:
    path:     /rejestracja
    defaults: { _controller: MyKilometrowkaBundle:Default:rejestracja }
    
my_kilometrowka_logowanie:
    path:     /logowanie
    defaults: { _controller: MyKilometrowkaBundle:Default:logowanie }
    
my_kilometrowka_info:
    path:     /info
    defaults: { _controller: MyKilometrowkaBundle:Default:info }
    
my_kilometrowka_wyloguj:
    path:     /wyloguj
    defaults: { _controller: MyKilometrowkaBundle:Default:wyloguj }
    
#    kontroler LoginController

my_kilometrowka_zalogowany_ewidencja:
    path:     /ewidencja
    defaults: { _controller: MyKilometrowkaBundle:Login:ewidencja }
    
my_kilometrowka_zalogowany_ewidencjaNr:
    path:     /ewidencjaNr/{idFirmy}/{idPojazdu}/{rok}/{miesiac}/{raport}
    defaults: { _controller: MyKilometrowkaBundle:Login:ewidencjaNr, raport: -1 }
    
my_kilometrowka_zalogowany_przejazdy:
    path:     /przejazdy
    defaults: { _controller: MyKilometrowkaBundle:Login:przejazdy }
    
my_kilometrowka_zalogowany_pracownicy:
    path:     /pracownicy
    defaults: { _controller: MyKilometrowkaBundle:Login:pracownicy }
    
my_kilometrowka_zalogowany_pojazdy:
    path:     /pojazdy
    defaults: { _controller: MyKilometrowkaBundle:Login:pojazdy }

my_kilometrowka_zalogowany_trasy:
    path:     /trasy
    defaults: { _controller: MyKilometrowkaBundle:Login:trasy }
    
my_kilometrowka_zalogowany_firmy:
    path:     /firmy
    defaults: { _controller: MyKilometrowkaBundle:Login:firmy }


my_kilometrowka_zalogowany_usun:
    path:     /usun/{id}/{typ}
    defaults: { _controller: MyKilometrowkaBundle:Login:usun }
    
my_kilometrowka_zalogowany_dodajFirme:
    path:     /dodajFirme/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajFirme, id: -1}
    
    
my_kilometrowka_zalogowany_edytujFirme:
    path:     /edytujFirme/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajFirme }
    
my_kilometrowka_zalogowany_dodajTrase:
    path:     /dodajTrase/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajTrase, id: -1}
    
    
my_kilometrowka_zalogowany_edytujTrase:
    path:     /edytujTrase/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajTrase }
    
    
my_kilometrowka_zalogowany_dodajPojazd:
    path:     /dodajPojazd/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPojazd, id: -1}
    
    
my_kilometrowka_zalogowany_edytujPojazd:
    path:     /edytujPojazd/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPojazd }
    
my_kilometrowka_zalogowany_dodajPracownika:
    path:     /dodajPracownika/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPracownika, id: -1}
    
    
my_kilometrowka_zalogowany_edytujPracownika:
    path:     /edytujPracownika/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPracownika }
    
my_kilometrowka_zalogowany_dodajPrzejazd:
    path:     /dodajPrzejazd/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPrzejazd, id: -1}
    
    
my_kilometrowka_zalogowany_edytujPrzejazd:
    path:     /edytujPrzejazd/{id}
    defaults: { _controller: MyKilometrowkaBundle:Login:dodajPrzejazd }