My\KilometrowkaBundle\Entity\Trasa:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nazwa:
            type: string
            length: '15'
        skad:
            type: string
            length: '64'
        dokad:
            type: string
            length: '64'
        odleglosc:
            type: string
            length: '9'
        opis:
            type: string
            length: 255
        idUzytkownika:
            type: integer
    lifecycleCallbacks: {  }
