CREATE TABLE `firma` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nazwaFirmy` VARCHAR(128) COLLATE UTF8_UNICODE_CI NOT NULL,
    `adres` VARCHAR(128) COLLATE UTF8_UNICODE_CI NOT NULL,
    `miasto` VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL,
    `kodPocztowy` VARCHAR(6) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nip` VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL,
    `regon` VARCHAR(14) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idUzytkownika` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=99 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

CREATE TABLE `pojazd` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `stawka` DOUBLE NOT NULL,
    `nazwa` VARCHAR(15) COLLATE UTF8_UNICODE_CI NOT NULL,
    `numerRejestracyjny` VARCHAR(10) COLLATE UTF8_UNICODE_CI NOT NULL,
    `pojemnoscSilnika` VARCHAR(1) COLLATE UTF8_UNICODE_CI NOT NULL,
    `opis` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idUzytkownika` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=33 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

	CREATE TABLE `pracownik` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `imie` VARCHAR(22) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nazwisko` VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL,
    `adres` VARCHAR(128) COLLATE UTF8_UNICODE_CI NOT NULL,
    `miasto` VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL,
    `kodPocztowy` VARCHAR(6) COLLATE UTF8_UNICODE_CI NOT NULL,
    `telefon` VARCHAR(20) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idUzytkownika` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=19 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

CREATE TABLE `przejazd` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `idPojazdu` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idTrasy` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idFirmy` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idPracownika` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `celWyjazdu` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `adnotacje` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `data` DATE NOT NULL,
    `odlegloscTrasy` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nazwaPojazdu` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nazwaFirmy` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nazwaPracownika` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `nazwaTrasy` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `miesiacIRok` DATE NOT NULL,
    `cena` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idUzytkownika` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=134 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

	CREATE TABLE `trasa` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `nazwa` VARCHAR(15) COLLATE UTF8_UNICODE_CI NOT NULL,
    `skad` VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL,
    `dokad` VARCHAR(64) COLLATE UTF8_UNICODE_CI NOT NULL,
    `odleglosc` VARCHAR(9) COLLATE UTF8_UNICODE_CI NOT NULL,
    `opis` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `idUzytkownika` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=27 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;

	CREATE TABLE `user` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `login` VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL,
    `haslo` VARCHAR(32) COLLATE UTF8_UNICODE_CI NOT NULL,
    `email` VARCHAR(255) COLLATE UTF8_UNICODE_CI NOT NULL,
    `zalogowany` TINYINT(1) NOT NULL,
    PRIMARY KEY (`id`)
)  ENGINE=INNODB AUTO_INCREMENT=16 DEFAULT CHARSET=UTF8 COLLATE = UTF8_UNICODE_CI;