parameters:
#    my_kilometrowka.example.class: My\KilometrowkaBundle\Example

services:
#    my_kilometrowka.example:
#        class: %my_kilometrowka.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
