My\KilometrowkaBundle\Entity\Firma:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nazwaFirmy:
            type: string
            length: '128'
        adres:
            type: string
            length: '128'
        miasto:
            type: string
            length: '64'
        kodPocztowy:
            type: string
            length: '6'
        nip:
            type: string
            length: '32'
        regon:
            type: string
            length: '14'
        idUzytkownika:
            type: integer
    lifecycleCallbacks: {  }
