My\KilometrowkaBundle\Entity\Pojazd:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        stawka:
            type: float
        nazwa:
            type: string
            length: '15'
        numerRejestracyjny:
            type: string
            length: '10'
        pojemnoscSilnika:
            type: string
            length: '1'
        opis:
            type: string
            length: 255
        idUzytkownika:
            type: integer
    lifecycleCallbacks: {  }
