My\KilometrowkaBundle\Entity\Przejazd:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idPojazdu:
            type: string
            length: 255
        idTrasy:
            type: string
            length: 255
        idFirmy:
            type: string
            length: 255
        idPracownika:
            type: string
            length: 255
        celWyjazdu:
            type: string
            length: 255
        adnotacje:
            type: string
            length: 255
        data:
            type: date
        odlegloscTrasy:
            type: string
            length: 255
        nazwaPojazdu:
            type: string
            length: 255
        nazwaFirmy:
            type: string
            length: 255
        nazwaPracownika:
            type: string
            length: 255
        nazwaTrasy:
            type: string
            length: 255
        miesiacIRok:
            type: date
        cena:
            type: string
            length: 255
        idUzytkownika:
            type: integer
    lifecycleCallbacks: {  }
