My\KilometrowkaBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        login:
            type: string
            length: '32'
        haslo:
            type: string
            length: '32'
        email:
            type: string
            length: 255
        zalogowany:
            type: boolean
    lifecycleCallbacks: {  }
